/* eslint-disable @typescript-eslint/no-explicit-any */
import {
  IconActivity,
  IconAdjustments,
  IconAnchor,
  IconArrowRight,
  IconAtom,
  IconAward,
  IconBolt,
  IconBrain,
  IconBrush,
  IconBulb,
  IconCamera,
  IconChartBar,
  IconChartLine,
  IconCircle,
  IconCode,
  IconCompass,
  IconCrosshair,
  IconCrown,
  IconCube,
  IconDatabase,
  IconDiamond,
  IconDroplet,
  IconEye,
  IconFeather,
  IconFilter,
  IconFlag,
  IconFlame,
  IconFocus,
  IconGlobe,
  IconHeart,
  IconInfinity,
  IconKey,
  IconLayersDifference,
  IconLeaf,
  IconLock,
  IconMap,
  IconMapPin,
  IconMedal,
  IconMicroscope,
  IconMoon,
  IconMountain,
  IconPalette,
  IconPencil,
  IconPlanet,
  IconPrism,
  IconRocket,
  IconSearch,
  IconSeeding,
  IconSettings,
  IconShield,
  IconSnowflake,
  IconSparkles,
  IconSquare,
  IconStack2,
  IconStar,
  IconSun,
  IconSwords,
  IconTarget,
  IconTree,
  IconTrendingUp,
  IconTrophy,
  IconUsers,
  IconWand,
  IconWaveSine,
  IconWind,
  IconBox,
  IconCircleCheck,
  IconCloud,
} from '@tabler/icons-react';
import { ComponentType } from 'react';

type TablerIcon = ComponentType<any>;

const ICON_MAP: Record<string, TablerIcon> = {
  'ti-activity':        IconActivity,
  'ti-adjustments':     IconAdjustments,
  'ti-anchor':          IconAnchor,
  'ti-arrow-right':     IconArrowRight,
  'ti-atom':            IconAtom,
  'ti-award':           IconAward,
  'ti-bolt':            IconBolt,
  'ti-brain':           IconBrain,
  'ti-brush':           IconBrush,
  'ti-bulb':            IconBulb,
  'ti-camera':          IconCamera,
  'ti-chart':           IconChartBar,
  'ti-chart-bar':       IconChartBar,
  'ti-chart-line':      IconChartLine,
  'ti-circle':          IconCircle,
  'ti-circle-check':    IconCircleCheck,
  'ti-cloud':           IconCloud,
  'ti-code':            IconCode,
  'ti-compass':         IconCompass,
  'ti-crosshair':       IconCrosshair,
  'ti-crown':           IconCrown,
  'ti-cube':            IconCube,
  'ti-database':        IconDatabase,
  'ti-diamond':         IconDiamond,
  'ti-droplet':         IconDroplet,
  'ti-eye':             IconEye,
  'ti-feather':         IconFeather,
  'ti-filter':          IconFilter,
  'ti-fire':            IconFlame,
  'ti-flag':            IconFlag,
  'ti-flame':           IconFlame,
  'ti-focus':           IconFocus,
  'ti-globe':           IconGlobe,
  'ti-heart':           IconHeart,
  'ti-infinity':        IconInfinity,
  'ti-key':             IconKey,
  'ti-layers':          IconLayersDifference,
  'ti-leaf':            IconLeaf,
  'ti-lightbulb':       IconBulb,
  'ti-lock':            IconLock,
  'ti-map':             IconMap,
  'ti-map-pin':         IconMapPin,
  'ti-medal':           IconMedal,
  'ti-microscope':      IconMicroscope,
  'ti-moon':            IconMoon,
  'ti-mountain':        IconMountain,
  'ti-palette':         IconPalette,
  'ti-pencil':          IconPencil,
  'ti-planet':          IconPlanet,
  'ti-prism':           IconPrism,
  'ti-pulse':           IconActivity,
  'ti-rocket':          IconRocket,
  'ti-search':          IconSearch,
  'ti-seeding':         IconSeeding,
  'ti-settings':        IconSettings,
  'ti-shield':          IconShield,
  'ti-sliders':         IconAdjustments,
  'ti-snowflake':       IconSnowflake,
  'ti-sparkles':        IconSparkles,
  'ti-square':          IconSquare,
  'ti-stack':           IconStack2,
  'ti-star':            IconStar,
  'ti-sun':             IconSun,
  'ti-swords':          IconSwords,
  'ti-target':          IconTarget,
  'ti-tree':            IconTree,
  'ti-trending-up':     IconTrendingUp,
  'ti-trophy':          IconTrophy,
  'ti-users':           IconUsers,
  'ti-box':             IconBox,
  'ti-wand':            IconWand,
  'ti-wave':            IconWaveSine,
  'ti-wind':            IconWind,
  'ti-zap':             IconBolt,
};

export function getTablerIcon(name: string): TablerIcon {
  return ICON_MAP[name] ?? IconStar;
}
